# Site settings
title: Raffaella Capasso
description: My Webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raffaellacapasso.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raffaella Capasso
user_description: >+
    I am an astrophysicist with a passion for data visualization and problem solving. Through big data processing, I am interested in understanding, extracting, and presenting the meaningful value hidden in data. <br />
        <br />
    Born and raised in Italy, I completed my undergraduate studies in Astrophysics and Cosmology at the Alma mater studiorum - University of Bologna. I then moved to Munich, Germany, where I obtained my PhD degree at the Ludwig-Maximilians-Universität. <br />
        <br />
    After a postdoc at Stockholm University, I am currently employed as a researcher at Ludwig-Maximilians-Universität, in the astrophysics, cosmology, and artificial intelligenc group of Prof. Daniel Gruen. My work focuses on observational and computational cosmology. I am interested in the study of cosmic large-scale structures, dynamics and formation of galaxies, and determination of the nature of dark matter and dark energy. <br />

user_title: Researcher · Data Scientist
email: rg.capasso@gmail.com
#twitter_username: lorem_ipsum
github_username:  RaCap
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
